We should be able to return more IPs
nixops check will fail if the machine is not up so maybe that's to check
first

    if ret is None: raise libvirtError ('virDomainInterfaceAddresses() failed', dom=self)
libvirtError: argument unsupported: QEMU guest agent is not configured
------------------------------
Traceback (most recent call last):
  File "/home/teto/nixops/nixops/parallel.py", line 41, in thread_fun
    result_queue.put((worker_fun(t), None))
  File "/home/teto/nixops/scripts/nixops", line 250, in worker
    res = m.check()
  File "/home/teto/nixops/nixops/backends/__init__.py", line 115, in check
    self._check(res)
  File "/home/teto/nixops/nixops/backends/__init__.py", line 119, in _check
    avg = self.get_load_avg()
  File "/home/teto/nixops/nixops/backends/__init__.py", line 102, in get_load_avg
    res = self.run_command("cat /proc/loadavg", capture_stdout=True, timeout=15).rstrip().split(' ')
  File "/home/teto/nixops/nixops/backends/__init__.py", line 328, in run_command
    return self.ssh.run_command(command, self.get_ssh_flags(), **kwargs)
  File "/home/teto/nixops/nixops/ssh_util.py", line 277, in run_command
    master = self.get_master(flags, timeout, user)
  File "/home/teto/nixops/nixops/ssh_util.py", line 188, in get_master
    if self._host_fun() == "localhost":
  File "/home/teto/nixops/nixops/backends/libvirtd.py", line 272, in get_ssh_name
    self.private_ipv4 = self._parse_ip()
  File "/home/teto/nixops/nixops/backends/libvirtd.py", line 222, in _parse_ip
    ifaces = self.dom.interfaceAddresses(libvirt.VIR_DOMAIN_INTERFACE_ADDRESSES_SRC_AGENT, 0)
  File "/nix/store/sv92y6wndbw8kl5cgiqxg71gi4i6dvnv-libvirt-python-3.6.0/lib/python2.7/site-packages/libvirt.py", line 1340, in interfaceAddresses
    if ret is None: raise libvirtError ('virDomainInterfaceAddresses() failed', dom=self)
libvirtError: argument unsupported: QEMU guest agent is not configured