deployment: avoid spurious warnings with --dry-run
Prior to this commit, error messages like:

    error: selector ‘’ matches no derivations
    error: cannot update profile ‘/nix/var/nix/profiles/per-user/_/nixops/_’

would be generated when invoking `nixops deploy --dry-run`.

This occurs because `nix-build --dry-run` does not return a configuration 
path, causing a subsequent `nix-env` to fail on the empty value.  We skip 
profile creation during dry runs to avoid this.

Closes #225.