Fix SSHKeyPairDefinition
The base `ResourceDefinition` class requires the `config` property's
type annotation to not be a string (added cd9319be1cc / a70af271557),
but the `ssh_keypair.py` module activates postponed annotations via the
`from __future__ import annotations` syntax (added e48422a9b0d), which
turns all type annotations in the module into strings[1], breaking the
`SSHKeyPairDefinition` class when initialized.

Thus any defined `resources.sshKeyPairs` break `nixops` commands,
causing failures with the message:

```
TypeError: <class 'nixops.resources.ssh_keypair.SSHKeyPairDefinition'>.config's type annotation is not allowed to be a string, see: https://nixops.readthedocs.io/en/latest/plugins/authoring.html
```

A number of possible workarounds for this, but the simplest would seem
to just not activate PEP 563-style postponed annotations in
`ssh_keypair.py`.

[1] https://peps.python.org/pep-0563/