eval-machine-info.nix: Fix nixpkgs setting
Fixes the errors encountered in the test suite:

error: --- EvalError ---------------- nix-instantiate
at: (51:26) in file: /home/user/h/nixops/nix/eval-machine-info.nix

    50|       else throw "NixOps network must have a 'nixpkgs' attribute"
    51|     else (builtins.head (network.network)).nixpkgs or (import <nixpkgs> { inherit system; });
      |                          ^
    52|

attribute 'network' missing