Revert "Set ec2.hvm. Needs latest 14.04/14.12/master to work with non-EC2 backends."
This reverts commit 49bb8b8c59bb55616825410edf53d164c66f06ef since it
breaks deploying nixos.org:

  webserver> copying 9 missing paths (2.07 MiB) to ‘root@54.217.220.47’...
  webserver> updating GRUB 2 menu...
  webserver> installing the GRUB 2 boot loader on /dev/xvda...
  webserver> Installing for i386-pc platform.
  webserver> /nix/store/969zn754v76hspiyn32bj44wf6yz1ia6-grub-2.02-git-1de3a4/sbin/grub-install: warning: File system `ext2' doesn't support embedding.
  webserver> /nix/store/969zn754v76hspiyn32bj44wf6yz1ia6-grub-2.02-git-1de3a4/sbin/grub-install: warning: Embedding is not possible.  GRUB can only be installed in this setup by using blocklists.  However, blocklists are UNRELIABLE and their use is discouraged..
  webserver> /nix/store/969zn754v76hspiyn32bj44wf6yz1ia6-grub-2.02-git-1de3a4/sbin/grub-install: error: will not proceed with blocklists.
  webserver> /nix/store/xcni2yv1dkbi07028rn7ha4cqiz3fv7b-install-grub.pl: installation of GRUB on /dev/xvda failed
  webserver> error: unable to activate new configuration
  error: activation of 1 of 1 machines failed (namely on ‘webserver’)

I.e. it caused a switch from GRUB 1 to 2, which doesn't work.

@rbvermaa